const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const candidateSchema = new Schema({
  email: { type: String, required: true },
  firstName: { type: String, required: true },
  middleName: { type: String },
  lastName: { type: String, required: true },
  contactNumber: { type: String, required: true },
  alternateContactNumber: { type: String },
  dateOfBirth: { type: Date, required: true },
  age: { type: Number, required: true },
  gender: { type: String, required: true },
  maritalStatus: { type: String, required: true },
  nationality: { type: String, required: true },
  streetAddress: { type: String, required: true },
  city: { type: String, required: true },
  state: { type: String, required: true },
  postalCode: { type: String, required: true },
  country: { type: String, required: true },
  hasPassport: { type: String, required: true },
  passportNumber: { type: String },
  aadhaarNumber: { type: String },
  panNumber: { type: String },
  drivingLicenseNumber: { type: String },
  voterIdNumber: { type: String },
  linkedInProfile: { type: String },
  socialMediaProfiles: { type: String },
  onlinePortfolio: { type: String },
  skills: { type: String },
  languages: { type: String },
  educationCourse: { type: String },
  educationSpecialization: { type: String },
  educationInstitution: { type: String },
  educationYearOfCompletion: { type: String },
  educationPassPercentage: { type: String },
  certifications: { type: String },
  certificationsList: { type: String },
  certificationIssuingAuthority: { type: String },
  certificationCompletionDate: { type: Date },
  expectedJoiningDate: { type: Date },
  fresher: { type: String },
  backgroundCheckConsent: { type: String },
  drugAlcoholTestingConsent: { type: String },
  criminalConvictionsDisclosure: { type: String },
  acknowledgement: { type: String },
});

module.exports = mongoose.model('Candidate', candidateSchema);
